### ISSUE TITLE
Could not download TalsecSecurity-Community-6.0.0-release.aar

### ISSUE THREAD

**Issue by xavieaihh** [talsec/Free-RASP-Android#15]
**Describe the bug**
Hi there, hope you're doing well :)

So , I'm trying to install your library into my app and I got this error: 
Could not download TalsecSecurity-Community-6.0.0-release.aar

**To Reproduce**
I followed your installation guide, and then I "Make project" into Android Studio 
Actually I had to add those dependencies as well in addition to yours:

    implementation 'com.huawei.hms:safetydetect:6.7.0.300'
    implementation 'com.madgag.spongycastle:core:1.54.0.0'
    implementation 'com.madgag.spongycastle:prov:1.54.0.0'
    implementation 'com.madgag.spongycastle:pkix:1.54.0.0'
    implementation 'com.madgag.spongycastle:pg:1.54.0.0'

I then checked the link you provided :

url "https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp"

And this one gives a 400 error might be the cause ?

So I tried with the link you provided in another ticket resolution where it is question of nexus link and this one is actually working but not enough for my project to be able to download the community version :/ 

**Expected behavior**
If you could give me a hand to solve this installation's issue I would be very grateful ;)

In advance Cheers for your time

**Screenshots**

Execution failed for task ':my-app:dataBindingMergeDependencyArtifactsGplayDebug'.
> Could not resolve all files for configuration ':my-app:gplayDebugCompileClasspath'.
   > Failed to transform TalsecSecurity-Community-6.0.0-release.aar (com.aheaditec.talsec.security:TalsecSecurity-Community:6.0.0-release) to match attributes {artifactType=android-databinding, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not download TalsecSecurity-Community-6.0.0-release.aar (com.aheaditec.talsec.security:TalsecSecurity-Community:6.0.0-release)

**Please complete the following information:**
 - Version of freeRASP:  6.0.0

**Comment by msikyna** [comment]
Hello @xavieaihh ,
we will look at the issue and get back to you.
Kind regards,
Talsec team

**Comment by msikyna** [comment]
Hello @xavieaihh ,
a new version has been released. Does the issue still persist?
Kind regards,
Talsec team

**Comment by Neustradamus** [comment]
There are a lot of CVE in Spongy Castle, can you update to last Bouncy Castle version?
- https://www.bouncycastle.org/releasenotes.html

**Comment by msikyna** [comment]
https://github.com/talsec/Free-RASP-ReactNative/issues/13#issuecomment-1563963518

**Comment by rpavliuk** [comment]
Hi, I have a similar issue:
`Connect to nexus3-public.monetplus.cz:443 [nexus3-public.monetplus.cz/193.33.22.117] failed: Connect timed out`

I've added everything according to the docs:

```kotlin
// in my case in settings.gradle.kts
maven { url = uri("https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp") }

// app module
implementation("com.aheaditec.talsec.security:TalsecSecurity-Community:7.0.0")

```
Any hints on how to fix this?
Or I just need to wait for the next release next week?

**Comment by msikyna** [comment]
Hello @rpavliuk and @arshakavag92 , 

There is an internal infrastructure issue with the Nexus repository. It is indeed down. We are working on the fix, stay tuned!

Kind regards,
Talsec team

**Comment by msikyna** [comment]
Hello @rpavliuk , @arshakavag92 ,

the issue has been resolved. Could you try again? Thank you.

**Comment by rpavliuk** [comment]
@msikyna I still have this issue:
`nexus3-public.monetplus.cz:443 [nexus3-public.monetplus.cz/193.33.22.117] failed: Connect timed out`

but my whole log is kinda strange. I dunno why but I'm getting mixed result of Glide and your URL. Maybe this is some bug with AndroidStudio or Gradle.
`Could not determine the dependencies of task ':utils:kspDebugKotlin'.
> Could not resolve all task dependencies for configuration ':utils:kspDebugKotlinProcessorClasspath'.
   > Could not resolve com.github.bumptech.glide:ksp:4.15.0.
     Required by:
         project :utils
      > Could not resolve com.github.bumptech.glide:ksp:4.15.0.
         > Could not get resource 'https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp/com/github/bumptech/glide/ksp/4.15.0/ksp-4.15.0.pom'.
            > Could not HEAD 'https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp/com/github/bumptech/glide/ksp/4.15.0/ksp-4.15.0.pom'.
               > Connect to nexus3-public.monetplus.cz:443 [nexus3-public.monetplus.cz/193.33.22.117] failed: Connect timed out`

**Comment by rpavliuk** [comment]
here's my setup:
`dependencyResolutionManagement {

    val props = getPropertiesFile()

    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        maven { url = uri("https://maven.google.com/") }
        maven { url = uri("https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp") }
        maven { url = uri("https://jitpack.io") }
        maven {
            url = uri("https://artifactory.infrateam.xyz/artifactory/gradle-mobile")
            credentials {
                username = props.getProperty("artifactory.login")
                password = props.getProperty("artifactory.password")
            }
        }
        maven {
            url = uri("https://pkgs.dev.azure.com/MicrosoftDeviceSDK/DuoSDK-Public/_packaging/Duo-SDK-Feed/maven/v1")
        }
        mavenCentral()
    }
}`

**Comment by rpavliuk** [comment]
@msikyna it worked.
I was trying to do this earlier but your repo was put before the mavenCentral and this failed work. It should be the last on the list.
Thanks for pushing me to try again :)

**Comment by msikyna** [comment]
@rpavliuk 
thank you for brining up the issue. We will add this info into the documentation, it is not clear enough that it should be put after mavenCentral().
